local ADDON_NAME, KeyLab = ...
KeyLab = KeyLab or {}
_G.KeyLab = KeyLab

KeyLab.Mapping = KeyLab.Mapping or {}

--[[
KeyLab Affix Mapping

Purpose:
- Maps affix IDs to KeyLab names/descriptions.
- Capture stores raw affix IDs only.
- UI uses this file for display text later.
]]

KeyLab.Mapping.Affixes = {
    [1] = { keylabKey = "affix1", name = "Overflowing", description = "Healing in excess of a target's maximum health is instead converted to a heal absorption effect.", store = true },
    [2] = { keylabKey = "affix2", name = "Skittish", description = "Enemies pay far less attention to threat generated by tanks.", store = true },
    [3] = { keylabKey = "affix3", name = "Volcanic", description = "While in combat, enemies periodically cause gouts of flame to erupt beneath the feet of distant players.", store = true },
    [4] = { keylabKey = "affix4", name = "Necrotic", description = "All enemies' melee attacks apply a stacking blight that inflicts damage over time and reduces healing received.", store = true },
    [5] = { keylabKey = "affix5", name = "Teeming", description = "Additional non-boss enemies are present throughout the dungeon.", store = true },
    [6] = { keylabKey = "affix6", name = "Raging", description = "Non-boss enemies enrage at 30% health remaining, temporarily granting immunity to crowd control effects.", store = true },
    [7] = { keylabKey = "affix7", name = "Bolstering", description = "When any non-boss enemy dies, its death cry empowers nearby allies, temporarily increasing their health by 10%.", store = true },
    [8] = { keylabKey = "affix8", name = "Sanguine", description = "When slain, non-boss enemies leave behind a lingering pool of ichor that heals their allies and damages players.", store = true },
    [9] = { keylabKey = "affix9", name = "Tyrannical", description = "Bosses have 25% more health. Bosses and their minions inflict up to 15% increased damage.", store = true },
    [10] = { keylabKey = "affix10", name = "Fortified", description = "Non-boss enemies have 20% more health and inflict up to 20% increased damage.", store = true },
    [11] = { keylabKey = "affix11", name = "Bursting", description = "When slain, non-boss enemies explode, causing all players to suffer damage over 4 sec. This effect stacks.", store = true },
    [12] = { keylabKey = "affix12", name = "Grievous", description = "Injured players suffer increasing damage over time until healed.", store = true },
    [13] = { keylabKey = "affix13", name = "Explosive", description = "While in combat, enemies periodically summon Explosive Orbs that will detonate if not destroyed.", store = true },
    [14] = { keylabKey = "affix14", name = "Quaking", description = "Periodically, all players emit a shockwave, inflicting damage and interrupting nearby allies.", store = true },
    [16] = { keylabKey = "affix16", name = "Infested", description = "Some non-boss enemies have been infested with a Spawn of G'huun.", store = true },
    [117] = { keylabKey = "affix117", name = "Reaping", description = "Non-boss enemies are empowered by Bwonsamdi and periodically seek vengeance from beyond the grave.", store = true },
    [119] = { keylabKey = "affix119", name = "Beguiling", description = "Azshara's Emissaries are present throughout the dungeon.", store = true },
    [120] = { keylabKey = "affix120", name = "Awakened", description = "Obelisks throughout the dungeon allow players to enter Ny'alotha and confront powerful servants of N'Zoth.", store = true },
    [121] = { keylabKey = "affix121", name = "Prideful", description = "Players overflow with pride as they defeat non-boss enemies.", store = true },
    [122] = { keylabKey = "affix122", name = "Inspiring", description = "Some non-boss enemies have an inspiring presence that strengthens their allies.", store = true },
    [123] = { keylabKey = "affix123", name = "Spiteful", description = "Fiends rise from the corpses of non-boss enemies and pursue random players.", store = true },
    [124] = { keylabKey = "affix124", name = "Storming", description = "While in combat, enemies periodically summon damaging whirlwinds.", store = true },
    [128] = { keylabKey = "affix128", name = "Tormented", description = "Servants of the Jailer can be found throughout the dungeon and grant powerful boons when defeated.", store = true },
    [129] = { keylabKey = "affix129", name = "Infernal", description = "Infernal Beacons can be found near some bosses.", store = true },
    [130] = { keylabKey = "affix130", name = "Encrypted", description = "Enemies throughout the dungeon possess relics of the First Ones.", store = true },
    [131] = { keylabKey = "affix131", name = "Shrouded", description = "Nathrezim infiltrators have disguised themselves among enemies throughout the dungeon.", store = true },
    [132] = { keylabKey = "affix132", name = "Thundering", description = "Enemies have 5% more health.", store = true },
    [133] = { keylabKey = "affix133", name = "Focused", description = "Non-boss enemies with mana have 30% increased Haste.", store = true },
    [134] = { keylabKey = "affix134", name = "Entangling", description = "While in combat, entangling vines periodically appear and snare players.", store = true },
    [135] = { keylabKey = "affix135", name = "Afflicted", description = "While in combat, afflicted souls periodically appear and seek the aid of players.", store = true },
    [136] = { keylabKey = "affix136", name = "Incorporeal", description = "While in combat, incorporeal beings periodically appear and attempt to weaken players.", store = true },
    [137] = { keylabKey = "affix137", name = "Shielding", description = "While in combat, enemies periodically summon Shielding Orbs.", store = true },
    [144] = { keylabKey = "affix144", name = "Thorned", description = "Non-boss enemies without mana inflict Physical damage to their attackers when attacked.", store = true },
    [145] = { keylabKey = "affix145", name = "Reckless", description = "Non-boss enemies without mana ignore 20% armor with their attacks.", store = true },
    [146] = { keylabKey = "affix146", name = "Attuned", description = "Non-boss enemies with mana inflict 20% increased magic damage.", store = true },
    [147] = { keylabKey = "affix147", name = "Xal'atath's Guile", description = "Xal'atath betrays players, revoking her bargains.", store = true },
    [148] = { keylabKey = "affix148", name = "Xal'atath's Bargain: Ascendant", description = "Xal'atath rains down orbs of cosmic energy.", store = true },
    [152] = { keylabKey = "affix152", name = "Challenger's Peril", description = "The timer is increased by 90 seconds, but deaths subtract time.", store = true },
    [153] = { keylabKey = "affix153", name = "Xal'atath's Bargain: Frenzied", description = "Non-boss enemies become frenzied at low health.", store = true },
    [158] = { keylabKey = "affix158", name = "Xal'atath's Bargain: Voidbound", description = "Xal'atath summons a Voidbound Emissary.", store = true },
    [159] = { keylabKey = "affix159", name = "Xal'atath's Bargain: Oblivion", description = "Xal'atath manifests crystals from the void.", store = true },
    [160] = { keylabKey = "affix160", name = "Xal'atath's Bargain: Devour", description = "Xal'atath tears open rifts that devour player essence.", store = true },
    [162] = { keylabKey = "affix162", name = "Xal'atath's Bargain: Pulsar", description = "Xal'atath summons pulsars that orbit players.", store = true },
    [165] = { keylabKey = "affix165", name = "Lindormi's Guidance", description = "Lindormi highlights and weakens specific enemies.", store = true },
    [166] = { keylabKey = "affix166", name = "Eternus's Trial: Sands of Time", description = "Eternus manifests bronze orbs during combat.", store = true },
    [167] = { keylabKey = "affix167", name = "Eternus's Trial: Dusk of the Infinite", description = "Eternus calls forth infinite dragonflight ambushes.", store = true },
    [168] = { keylabKey = "affix168", name = "Eternus's Trial: Timeways Manifested", description = "Eternus summons splitting elementals.", store = true },
    [169] = { keylabKey = "affix169", name = "Eternus's Trial: Twilight Reflections", description = "Eternus beckons alternate evil versions of players.", store = true },
    [170] = { keylabKey = "affix170", name = "Tyrannically Fortified", description = "Bosses and non-boss enemies are both empowered.", store = true },
}

function KeyLab.Mapping.GetAffixName(affixID)
    local entry = affixID and KeyLab.Mapping.Affixes[affixID]
    return entry and entry.name or nil
end

function KeyLab.Mapping.GetAffixDescription(affixID)
    local entry = affixID and KeyLab.Mapping.Affixes[affixID]
    return entry and entry.description or nil
end